version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    restart: always
    networks:
      - backend-network
      - app-network
    ports:
      - "3001:3001"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_NAME=itemsdb
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - backend-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: itemsdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppassword || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

networks:
  backend-network:
    driver: bridge
  app-network:
    name: app-network
    driver: bridge

volumes:
  mysql_data: