services:
  - type: web
    name: backend-service
    env: docker
    region: oregon  # Cambia esto según tu preferencia
    plan: free  # O cambia a un plan de pago si lo necesitas
    branch: main
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: mysql
      - key: DB_HOST
        sync: false  # Esto significa que deberás configurar manualmente este valor en Render
      - key: DB_PORT
        value: 3306
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: itemsdb

databases:
  - name: backend_db
    databaseName: backend_db
    user: backend_user